kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: featurehub-cluster
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
    - containerPort: 443
      hostPort: 443
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
#  - role: worker
