version: '3.1'

services:
  pubsub:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:398.0.0-emulators
    restart: always
    command:
      - gcloud
      - beta
      - emulators
      - pubsub
      - start
      - --project=featureuhb
      - --host-port=0.0.0:8075

  party-server:
    image: featurehub/party-server:latest
    restart: always
    user: 999:999
#    volumes:
#      - ./common-config:/etc/common-config
    environment:
      server.port: 8085
    env_file:
      - ./common.env
    ports:
      - 8085:8085
      - 8701:8701
    depends_on:
      - "db"
      - "pubsub"

  # a second copy of the party server
#  mr-server2:
#    image: featurehub/party-server:latest
#    restart: always
#    user: 999:999
#    volumes:
#      - ./common-config:/etc/common-config
#    environment:
#      server.port: 8086
#    env_file:
#      - ./common.env
#    ports:
#      - 8086:8086
#    depends_on:
#      - "db"
#      - "pubsub"

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - featurehub-ps1-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  featurehub-ps1-db:
