apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  application.properties: |-
    db.url={{ .Values.db.url }}
    db.username={{ .Values.db.username }}
    db.connections={{ default 3 .Values.db.connections }}
    run.nginx=true
    server.port=8085
    monitor.port=8701
    server.gracePeriodInSeconds={{ default 10 .Values.managementRepository.shutdownGracePeriodInSeconds }}
    register.url={{ default "http://localhost/register-url?token=%s" .Values.managementRepository.registrationUrl }}
    portfolio.admin.group.suffix={{ default "Administrators" .Values.managementRepository.portfolioGroupAdminSuffix }}

