apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "featurehub.fullname" . }}-management-repository-env
  labels:
    {{- include "featurehub.managementRepository.labels" . | nindent 4 }}
data:
{{- with .Values.managementRepository.environmentVars }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- if .Values.managementRepository.prometheus.enabled }}
  monitor.port: "8701"
{{- end }}
