apiVersion: v1
kind: Service
metadata:
  name: {{ include "featurehub.managementRepository.name" . }}
  labels:
    {{- include "featurehub.managementRepository.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "featurehub.managementRepository.selectorLabels" . | nindent 4 }}
