apiVersion: v1
kind: Secret
metadata:
  name: {{ include "featurehub.managementRepository.name" . }}-password-secret
# this should be mounted differently in your normal k8s mechanism, you will mount it
# from Cloud SQL or AWS RDS or similar
stringData:
  db.password: {{ .Values.db.password }}
