version: '3.1'

services:
  db:
    image: mysql:8.0.30
    restart: always
    environment:
      MYSQL_DATABASE: featurehub
      MYSQL_USER: featurehub
      MYSQL_PASSWORD: featurehub
      MYSQL_ROOT_PASSWORD: mypassword
    volumes:
      - featurehub-mysql-db:/var/lib/mysql
    ports:
      - 3324:3306

  party-server:
    image: featurehub/party-server:latest
    restart: always
    user: 999:999
    volumes:
      - ./app-config:/etc/app-config
    ports:
      - 8085:8085
      - 8701:8701
    depends_on:
      - "db"

volumes:
  featurehub-mysql-db:
