version: '3.1'

services:
  nats:
    image: nats:2.9.1-alpine
    restart: always
  mr-server:
    image: featurehub/mr:1.5.9-RC
    restart: always
    user: 999:999
    volumes:
      - ./app-config:/etc/app-config
    ports:
      - 8085:8085
      - 8701:8701
    depends_on:
      - "db"
      - "nats"
  dacha:
    image: featurehub/dacha2:1.5.9-RC
    restart: always
    user: 999:999
    volumes:
      - ./dacha-config:/etc/app-config
    depends_on:
      - "mr-server"
      - "nats"
    ports:
      - 8902:8902
      - 8703:8279
  edge:
    image: featurehub/edge:1.5.9-RC
    restart: always
    user: 999:999
    volumes:
      - ./edge-config:/etc/app-config
# use the below if you wish to override the logs
#      - ./common-config:/etc/common-config
    ports:
      - 8553:8553
      - 8702:8701
    depends_on:
      - "nats"
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - featurehub-ps1-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  featurehub-ps1-db:
