{{- if .Values.dacha.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "featurehub.dacha.name" . }}
  labels:
    {{- include "featurehub.dacha.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dacha.replicaCount }}
  {{- with .Values.dacha.strategy }}
  strategy:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "featurehub.dacha.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/dacha-env: {{ include (print $.Template.BasePath "/dacha/configmap-env.yaml") . | sha256sum }}

        {{- if and .Values.dacha.envAsApplicationProperties .Values.dacha.environmentVars }}
        checksum/dacha-app-config: {{ include (print $.Template.BasePath "/dacha/configmap-app-config.yaml") . | sha256sum }}
        {{- end }}

        {{- if .Values.global.environmentVars }}
        checksum/global-common-env: {{ include (print $.Template.BasePath "/common/configmap-global-common-env.yaml") . | sha256sum }}
        {{- end }}

        {{- if and .Values.global.envAsApplicationProperties .Values.global.environmentVars }}
        checksum/global-common-config: {{ include (print $.Template.BasePath "/common/configmap-global-common-config.yaml") . | sha256sum }}
        {{- end }}

        {{- if gt ( len .Values.global.extraCommonConfigFiles ) 0 }}
        checksum/global-common-config-extra: {{ include (print $.Template.BasePath "/common/configmap-global-common-config-extra.yaml") . | sha256sum }}
        {{- end }}

        {{- range $key, $value := .Values.dacha.podAnnotations }}
        {{ $key }}: {{ $value}}
        {{- end }}
      labels:
        {{- include "featurehub.dacha.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.dacha.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "featurehub.dacha.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.dacha.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "featurehub.dacha.name" . }}
          securityContext:
            {{- toYaml .Values.dacha.securityContext | nindent 12 }}
          image: "{{ .Values.dacha.image.repository }}:{{ .Values.dacha.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dacha.pullPolicy }}
          {{- if or (.Values.global.environmentVars) (.Values.dacha.environmentVars) (.Values.dacha.envFromSecret) }}
          envFrom:
            {{- if .Values.global.environmentVars }}
            - configMapRef:
                name: {{ include "featurehub.fullname" . }}-global-common-env
            {{- end }}
            {{- if .Values.dacha.environmentVars }}
            - configMapRef:
                name: {{ include "featurehub.fullname" . }}-dacha-env
            {{- end }}
            {{- if .Values.dacha.envFromSecret }}
            - secretRef:
                name: {{ .Values.dacha.envFromSecret }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8600
              protocol: TCP
            - name: metrics
              containerPort: 8701
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 2
            timeoutSeconds: 3
            httpGet:
              path: /health/liveness
              port: metrics
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 20
            successThreshold: 2
            failureThreshold: 2
            timeoutSeconds: 3
            httpGet:
              path: /health/readiness
              port: metrics
          volumeMounts:
          {{- if gt ( len .Values.global.extraCommonConfigFiles ) 0 -}}
          {{- range $cm := .Values.global.extraCommonConfigFiles }}
            - name: {{ $cm.configMapSuffix }} 
              mountPath: "/etc/common-config/{{ $cm.fileName }}"
              subPath: {{ $cm.fileName | quote }}
          {{- end }}
          {{- end }}
          {{- if and .Values.global.envAsApplicationProperties .Values.global.environmentVars }}
            - mountPath: /etc/common-config/common.properties
              name: common-config
              subPath: common.properties
          {{- else }}
            - mountPath: /etc/common-config
              name: common-config-empty
          {{- end }}
          {{- if and .Values.dacha.envAsApplicationProperties .Values.dacha.environmentVars }}
            - mountPath: /etc/app-config/application.properties
              name: app-config
              subPath: application.properties
          {{- else }}
            - mountPath: /etc/app-config
              name: app-config-empty
          {{- end }}
          {{- if .Values.dacha.extraVolumeMounts }}
            {{- toYaml .Values.dacha.extraVolumeMounts | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.dacha.resources | nindent 12 }}
      {{- with .Values.dacha.extraContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if gt ( len .Values.global.extraCommonConfigFiles ) 0 -}}
      {{- range $cm := .Values.global.extraCommonConfigFiles }}
      {{- with $ }}
        - name: {{ $cm.configMapSuffix }}
          configMap:
            name: {{ include "featurehub.fullname" . }}-global-extra-{{ $cm.configMapSuffix }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if and .Values.global.envAsApplicationProperties .Values.global.environmentVars }}
        - name: common-config
          configMap:
            name: {{ include "featurehub.fullname" . }}-global-common-config
            items:
              - key: common.properties
                path: common.properties
      {{- else }}
        - name: common-config-empty
          emptyDir: {}
      {{- end }}
      {{- if and .Values.dacha.envAsApplicationProperties .Values.dacha.environmentVars }}
        - name: app-config
          configMap:
            name: {{ include "featurehub.fullname" . }}-dacha-app-config
            items:
              - key: application.properties
                path: application.properties
      {{- else }}
        - name: app-config-empty
          emptyDir: {}
      {{- end }}
      {{- if .Values.dacha.extraVolumes }}
        {{- toYaml .Values.dacha.extraVolumes | nindent 8 }}
      {{- end }}
      {{- with .Values.dacha.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dacha.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dacha.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
