{{- if .Values.dacha.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "featurehub.dacha.name" . }}
  labels:
    {{- include "featurehub.dacha.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dacha.replicaCount }}
  selector:
    matchLabels:
      {{- include "featurehub.dacha.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/common-config: {{ include (print $.Template.BasePath "/common-config.yaml") . | sha256sum }}
        checksum/dacha-config: {{ include (print $.Template.BasePath "/dacha/configmap-env.yaml") . | sha256sum }}
        {{- range $key, $value := .Values.dacha.podAnnotations }}
        {{ $key }}: {{ $value}}
        {{- end }}
      labels:
        {{- include "featurehub.dacha.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.dacha.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "featurehub.dacha.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.dacha.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "featurehub.dacha.name" . }}
          securityContext:
            {{- toYaml .Values.dacha.securityContext | nindent 12 }}
          image: "{{ .Values.dacha.image.repository }}:{{ .Values.dacha.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dacha.pullPolicy }}
          {{- if or (.Values.dacha.environmentVars) (.Values.dacha.envFromSecret) }}
          envFrom:
            {{- if .Values.dacha.environmentVars }}
            - configMapRef:
                name: {{ include "featurehub.fullname" . }}-dacha-env
            {{- end }}
            {{- if .Values.dacha.envFromSecret }}
            - secretRef:
                name: {{ .Values.dacha.envFromSecret }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8600
              protocol: TCP
            - name: metrics
              containerPort: 8701
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 2
            timeoutSeconds: 3
            httpGet:
              path: /health/liveness
              port: metrics
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 20
            successThreshold: 2
            failureThreshold: 2
            timeoutSeconds: 3
            httpGet:
              path: /health/readiness
              port: metrics
          volumeMounts:
            - mountPath: /etc/common-config
              name: common-config
          resources:
            {{- toYaml .Values.dacha.resources | nindent 12 }}
      volumes:
        - name: common-config
          configMap:
            name: {{ include "featurehub.fullname" . }}-common-config
      {{- with .Values.dacha.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dacha.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dacha.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
