{{- if .Values.dacha.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "featurehub.dacha.name" . }}
  labels:
    {{- include "featurehub.dacha.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8600
      targetPort: http
      protocol: TCP
      name: http
  {{- if .Values.dacha.prometheus.enabled }}
    - port: 8701
      targetPort: metrics
      protocol: TCP
      name: metrics
  {{- end }}  
  selector:
    {{- include "featurehub.dacha.selectorLabels" . | nindent 4 }}
{{- end }}
