version: '3.1'

services:
  localstack:
    image: localstack/localstack:1.1
    restart: always
    ports:
      - 4566:4566
    environment:
      SERVICES: kinesis,dynamodb,cloudwatch
      KINESIS_PROVIDER: kinesis-mock
      KINESIS_INITIALIZE_STREAMS: featurehub-mr-edge,featurehub-stats,featurehub-mr-dacha2,featurehub-edge-updates
      LS_LOG: warn

  mr-server:
    image: featurehub/mr:latest
    restart: always
    user: 999:999
    volumes:
      - ./common-config:/etc/common-config
    env_file:
      - ./common.env
      - ./mr-config/application.env
    ports:
      - 8085:8085
    depends_on:
      - "db"
      - "localstack"
  dacha:
    image: featurehub/dacha2:latest
    restart: always
    user: 999:999
    volumes:
      - ./common-config:/etc/common-config
    env_file:
      - ./common.env
      - ./dacha-config/application.env
    depends_on:
      - "mr-server"
      - "localstack"
    ports:
      - 8902:8902
  edge:
    image: featurehub/edge:latest
    restart: always
    user: 999:999
    volumes:
      - ./common-config:/etc/common-config
    env_file:
      - ./common.env
      - ./edge-config/application.env
    ports:
      - 8553:8553
    depends_on:
      - "localstack"
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - featurehub-ps1-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  featurehub-ps1-db:
