apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: featurehub-db-service
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
      nodePort: 30003
  selector:
    io.kompose.service: db
status:
  loadBalancer: {}
