apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: featurehub-service
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: party-server
  name: party-server
spec:
  type: {{ .Values.partyServer.service.type }}
  ports:
    - name: http
      port: 8085
      targetPort: 8085
      protocol: TCP
      nodePort: 30002
  selector:
    io.kompose.service: party-server
status:
  loadBalancer: {}
