{{- if gt ( len .Values.global.extraCommonConfigFiles ) 0 }}
{{- range $cm := .Values.global.extraCommonConfigFiles }}
{{- with $ }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "featurehub.fullname" . }}-global-extra-{{ $cm.configMapSuffix }}
  labels:
    {{- include "featurehub.managementRepository.labels" . | nindent 4 }}
data:
  {{ $cm.fileName }}: {{- toYaml $cm.content | indent 2}}
---
{{- end }}
{{- end -}}
{{- end }}
