{{- if .Values.edge.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "featurehub.fullname" . }}-edge-env
  labels:
    {{- include "featurehub.edge.labels" . | nindent 4 }}
data:
{{- with .Values.edge.environmentVars }}
  {{- toYaml . | nindent 2 }}
{{- end }}
  monitor.port: "8701"
  server.port: "8553"
{{- end }}
