{{- if .Values.edge.enabled }}
{{- if .Values.edge.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "featurehub.edge.serviceAccountName" . }}
  labels:
  {{- with .Values.edge.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
