{{- if .Values.managementRepository.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "featurehub.fullname" . }}-management-repository-env
  labels:
    {{- include "featurehub.managementRepository.labels" . | nindent 4 }}
data:
{{- with .Values.managementRepository.environmentVars }}
  {{- toYaml . | nindent 2 }}
{{- end }}
  monitor.port: "8701"
  server.port: "8085"
  run.nginx: "true"
{{- end }}
