{{- if .Values.managementRepository.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "featurehub.managementRepository.name" . }}
  labels:
    {{- include "featurehub.managementRepository.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: http
      protocol: TCP
      name: http
  {{- if .Values.managementRepository.prometheus.enabled }}
    - port: 8701
      targetPort: metrics
      protocol: TCP
      name: metrics
  {{- end }}  
  selector:
    {{- include "featurehub.managementRepository.selectorLabels" . | nindent 4 }}
{{- end }}
