{{- if .Values.managementRepository.enabled }}
{{- if .Values.managementRepository.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "featurehub.managementRepository.serviceAccountName" . }}
  labels:
  {{- with .Values.managementRepository.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
