= Deploying FeatureHub on Kubernetes

These instructions are designed to get you up and running on a local kubernetes running on KinD. They will be
fleshed out over time as we have these examples running on Google's GKE/Autopilot, AWS's EKS/Fargate, and Azure's
AKS.

NOTE: This set of Helm charts is designed to be run the local kinD cluster and be fully operable by anyone following
these instructions. Without modification of the values in the charts, it is not intended to be production ready just
"go". That said, considerable effort has been put in by contributors to make this as easy to adapt to your needs as possible.

Please feel free to visit our https://docs.featurehub.io[documentation] for further information.

== Steps

=== 1. Install KinD

We assume KinD here rather than Docker for Kubernetes or Minikube or k3s. If you are familiar with those, you should
be able to use them too and you can skip this step.

If you don't have KinD installed, follow these instructions https://kind.sigs.k8s.io/docs/user/quick-start/#installation[KinD]

=== 2. Create the KinD cluster

[source,bash]
----
kind create cluster --config=kind-cluster.yaml
----

=== 3. Install Ingress - allow traffic into the cluster

[source,bash]
----
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml

kubectl wait --namespace ingress-nginx \
  --for=condition=ready pod \
  --selector=app.kubernetes.io/component=controller \
  --timeout=90s
----

=== 4. Install Chart dependencies

 $ cd featurehub && helm dependency update && cd ..

=== 5. Install FeatureHub (with defaults)

[source,bash]
----
helm upgrade --install featurehub featurehub
----

(If you receive an error 'Error: Internal error occurred: failed calling webhook ...', try deleting the ingress-nginx-admission
resource `kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission` and try again)


The FeatureHub services will initially 'crash' because they expect the Postgres and NATs services to already be available. Its
ok, they will recover fairly quickly and start up.

To update it with config changes, just

[source,bash]
----
helm upgrade featurehub featurehub
----

It should show something like this:

 $  kubectl get pods

----
NAME                                                READY   STATUS              RESTARTS   AGE
featurehub-dacha-7d65db8c48-r59l6                   0/1     Pending             0          7s
featurehub-dacha-7d65db8c48-zqb8s                   0/1     Running             0          8s
featurehub-edge-86b6b5cf46-4cqvr                    0/1     ContainerCreating   0          7s
featurehub-edge-86b6b5cf46-n8cm5                    0/1     ContainerCreating   0          8s
featurehub-management-repository-567b8fbffb-7vcbf   0/1     ContainerCreating   0          8s
featurehub-nats-0                                   0/3     ContainerCreating   0          8s
featurehub-nats-1                                   2/3     Running             0          7s
featurehub-nats-2                                   0/3     Pending             0          7s
featurehub-nats-box-78587c4478-nkbzt                0/1     ContainerCreating   0          8s
featurehub-postgresql-0                             0/1     Running             0          8s
----

=== 6. Test

It should be running on port 80, so you can login, create a new system, add features, etc. The Edge service is
also running on port 80.
