version: '3.8'

services:
  party-server:
    image: featurehub/party-server:latest
    restart: always
    user: 999:999
    volumes:
      - featurehub-h2-data:/db
      - ./app-config:/etc/app-config
      - ./common-config:/etc/common-config
    ports:
      - 8085:8085
      - 8701:8701
volumes:
  featurehub-h2-data:
