name: Release Charts

on:
  push:
    branches:
      - release-2.1.0
    paths:
      - 'helm/featurehub/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: Add Helm repositories
        run: |
          # Install yq tool to parse Chart.yaml to identify Helm dependencies repositories
          wget https://github.com/mikefarah/yq/releases/download/v4.21.1/yq_darwin_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq

          # Retrieve all helm dependencies repositories and run `helm repo add` for each of them.
          yq '.dependencies.[].repository' helm/featurehub/Chart.yaml | while read helm_repo; do
            # Helm repo name is generated from a random string, as it won't be persisted.
            helm repo add $(openssl rand -hex 12) ${helm_repo}
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.0
        with:
          charts_dir: helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          
